#!/bin/bash

if [ ! $# -eq 2]; then
  echo "two arguments needed" && exit 0
fi

if [ ! "$1" = "copy" ] && [ ! "$1" = "paste" ]; then
  echo "first argument has to be 'copy' or 'paste'" && exit 0
fi

if [ "$1" = "copy" ]; then
  docker exec $2 pg_dump -U dev postgres > /home/dev/.dbdumps/$2
  exit 0
fi

if [ $1 = "paste" ]; then
  #docker cp /home/dev/.dbdumps/$2 $2:/tmp/dumpfile_paste
  docker exec $2 psql -U dev postgres < /home/dev/.dbdumps/$2
  exit 0
fi
